// Code generated by goyacc -o grammar.go -p Doby grammar.y. DO NOT EDIT.

//line grammar.y:2

package parser

import __yyfmt__ "fmt"

//line grammar.y:3

import (
	"github.com/jxwr/doby/ast"
	"github.com/jxwr/doby/token"
)

var ProgramAst []ast.Stmt

type Tok struct {
	Lit  string
	Line int
	Col  int
	Pos  token.Pos
}

func (t Tok) String() string {
	return t.Lit
}

//line grammar.y:27
type DobySymType struct {
	yys        int
	node       ast.Node
	expr       ast.Expr
	expr_list  []ast.Expr
	stmt       ast.Stmt
	stmt_list  []ast.Stmt
	field      *ast.Field
	field_list []*ast.Field
	ident_list []*ast.Ident
	tok        Tok
}

const EOF = 57346
const EOL = 57347
const COMMENT = 57348
const IDENT = 57349
const INT = 57350
const FLOAT = 57351
const STRING = 57352
const CHAR = 57353
const SHL = 57354
const SHR = 57355
const AND_NOT = 57356
const ADD_ASSIGN = 57357
const SUB_ASSIGN = 57358
const MUL_ASSIGN = 57359
const QUO_ASSIGN = 57360
const REM_ASSIGN = 57361
const AND_ASSIGN = 57362
const OR_ASSIGN = 57363
const XOR_ASSIGN = 57364
const SHL_ASSIGN = 57365
const SHR_ASSIGN = 57366
const AND_NOT_ASSIGN = 57367
const LAND = 57368
const LOR = 57369
const ARROW = 57370
const INC = 57371
const DEC = 57372
const EQL = 57373
const NEQ = 57374
const LEQ = 57375
const GEQ = 57376
const DEFINE = 57377
const ELLIPSIS = 57378
const ADD = 57379
const SUB = 57380
const MUL = 57381
const QUO = 57382
const REM = 57383
const AND = 57384
const OR = 57385
const XOR = 57386
const LSS = 57387
const GTR = 57388
const ASSIGN = 57389
const NOT = 57390
const LPAREN = 57391
const LBRACK = 57392
const LBRACE = 57393
const COMMA = 57394
const PERIOD = 57395
const RPAREN = 57396
const RBRACK = 57397
const RBRACE = 57398
const SEMICOLON = 57399
const COLON = 57400
const BREAK = 57401
const CASE = 57402
const CHAN = 57403
const CONTINUE = 57404
const CONST = 57405
const DEFAULT = 57406
const DEFER = 57407
const ELSE = 57408
const FALLTHROUGH = 57409
const FOR = 57410
const FUNC = 57411
const GO = 57412
const GOTO = 57413
const IF = 57414
const IMPORT = 57415
const INTERFACE = 57416
const MAP = 57417
const PACKAGE = 57418
const RANGE = 57419
const RETURN = 57420
const SELECT = 57421
const STRUCT = 57422
const SWITCH = 57423
const TYPE = 57424
const VAR = 57425
const UMINUS = 57426

var DobyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EOF",
	"EOL",
	"COMMENT",
	"IDENT",
	"INT",
	"FLOAT",
	"STRING",
	"CHAR",
	"SHL",
	"SHR",
	"AND_NOT",
	"ADD_ASSIGN",
	"SUB_ASSIGN",
	"MUL_ASSIGN",
	"QUO_ASSIGN",
	"REM_ASSIGN",
	"AND_ASSIGN",
	"OR_ASSIGN",
	"XOR_ASSIGN",
	"SHL_ASSIGN",
	"SHR_ASSIGN",
	"AND_NOT_ASSIGN",
	"LAND",
	"LOR",
	"ARROW",
	"INC",
	"DEC",
	"EQL",
	"NEQ",
	"LEQ",
	"GEQ",
	"DEFINE",
	"ELLIPSIS",
	"ADD",
	"SUB",
	"MUL",
	"QUO",
	"REM",
	"AND",
	"OR",
	"XOR",
	"LSS",
	"GTR",
	"ASSIGN",
	"NOT",
	"LPAREN",
	"LBRACK",
	"LBRACE",
	"COMMA",
	"PERIOD",
	"RPAREN",
	"RBRACK",
	"RBRACE",
	"SEMICOLON",
	"COLON",
	"BREAK",
	"CASE",
	"CHAN",
	"CONTINUE",
	"CONST",
	"DEFAULT",
	"DEFER",
	"ELSE",
	"FALLTHROUGH",
	"FOR",
	"FUNC",
	"GO",
	"GOTO",
	"IF",
	"IMPORT",
	"INTERFACE",
	"MAP",
	"PACKAGE",
	"RANGE",
	"RETURN",
	"SELECT",
	"STRUCT",
	"SWITCH",
	"TYPE",
	"VAR",
	"UMINUS",
	"'#'",
}

var DobyStatenames = [...]string{}

const DobyEofCode = 1
const DobyErrCode = 2
const DobyInitialStackSize = 16

//line yacctab:1
var DobyExca = [...]int16{
	-1, 0,
	5, 122,
	57, 122,
	-2, 12,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 18,
	5, 72,
	51, 72,
	56, 72,
	57, 72,
	60, 72,
	64, 72,
	-2, 13,
	-1, 24,
	5, 122,
	56, 122,
	57, 122,
	-2, 12,
	-1, 54,
	1, 127,
	5, 126,
	57, 126,
	-2, 12,
	-1, 94,
	5, 88,
	51, 88,
	56, 88,
	57, 88,
	60, 88,
	64, 88,
	-2, 65,
	-1, 105,
	57, 72,
	-2, 13,
	-1, 158,
	5, 126,
	56, 126,
	57, 126,
	60, 126,
	64, 126,
	-2, 12,
	-1, 190,
	5, 122,
	56, 122,
	57, 122,
	60, 122,
	64, 122,
	-2, 12,
	-1, 211,
	5, 122,
	56, 122,
	57, 122,
	60, 122,
	64, 122,
	-2, 12,
}

const DobyPrivate = 57344

const DobyLast = 1131

var DobyAct = [...]uint8{
	97, 18, 11, 178, 176, 101, 188, 2, 163, 186,
	164, 81, 190, 166, 165, 81, 81, 211, 196, 171,
	202, 95, 239, 225, 30, 18, 99, 18, 158, 105,
	232, 54, 98, 202, 216, 226, 202, 81, 203, 58,
	57, 113, 114, 56, 162, 81, 24, 184, 102, 108,
	109, 110, 237, 198, 180, 18, 18, 3, 120, 158,
	123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
	133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
	55, 119, 143, 55, 100, 221, 103, 43, 44, 45,
	46, 47, 217, 43, 44, 45, 46, 47, 116, 164,
	199, 206, 159, 165, 200, 167, 160, 107, 168, 234,
	157, 55, 117, 118, 194, 177, 36, 223, 49, 204,
	1, 179, 183, 43, 49, 161, 17, 16, 50, 48,
	51, 15, 14, 13, 50, 48, 51, 94, 12, 81,
	115, 208, 218, 10, 9, 185, 61, 62, 63, 53,
	59, 60, 61, 62, 63, 53, 58, 57, 8, 18,
	56, 81, 58, 57, 195, 52, 56, 191, 19, 7,
	187, 52, 6, 59, 60, 61, 62, 63, 64, 65,
	66, 5, 207, 4, 205, 58, 57, 18, 175, 56,
	96, 18, 41, 18, 215, 40, 39, 106, 212, 177,
	177, 38, 222, 219, 220, 37, 224, 42, 35, 34,
	33, 32, 18, 31, 18, 0, 117, 230, 231, 228,
	111, 0, 177, 0, 0, 0, 233, 122, 0, 235,
	0, 0, 236, 43, 44, 45, 46, 47, 0, 0,
	0, 238, 240, 0, 210, 0, 0, 0, 0, 0,
	214, 145, 146, 147, 148, 149, 150, 151, 152, 153,
	154, 155, 156, 0, 49, 0, 0, 0, 0, 0,
	0, 229, 0, 0, 50, 48, 51, 24, 0, 0,
	0, 172, 173, 104, 0, 22, 0, 0, 23, 43,
	44, 45, 46, 47, 28, 53, 20, 0, 25, 29,
	0, 0, 0, 0, 21, 27, 0, 26, 0, 0,
	0, 52, 0, 43, 44, 45, 46, 47, 0, 174,
	49, 43, 44, 45, 46, 47, 0, 0, 0, 0,
	50, 48, 51, 189, 0, 0, 0, 0, 145, 0,
	0, 0, 0, 197, 49, 0, 0, 0, 0, 0,
	0, 53, 49, 0, 50, 48, 51, 24, 0, 193,
	0, 0, 50, 48, 51, 22, 0, 52, 23, 43,
	44, 45, 46, 47, 28, 53, 20, 0, 25, 29,
	0, 0, 0, 53, 21, 27, 0, 26, 0, 0,
	144, 52, 43, 44, 45, 46, 47, 0, 0, 52,
	49, 43, 44, 45, 46, 47, 0, 0, 0, 0,
	50, 48, 51, 112, 0, 43, 44, 45, 46, 47,
	121, 0, 0, 49, 0, 0, 0, 0, 0, 0,
	0, 53, 49, 50, 48, 51, 0, 0, 0, 0,
	0, 0, 50, 48, 51, 0, 49, 52, 59, 60,
	61, 62, 63, 64, 53, 66, 50, 48, 51, 0,
	58, 57, 0, 53, 56, 0, 0, 0, 0, 0,
	52, 0, 0, 0, 0, 0, 0, 53, 0, 52,
	67, 68, 69, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 52, 76, 77, 0, 0, 0, 75,
	72, 73, 74, 0, 0, 59, 60, 61, 62, 63,
	64, 65, 66, 70, 71, 0, 0, 58, 57, 0,
	0, 56, 0, 182, 0, 0, 181, 67, 68, 69,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 76, 77, 0, 0, 0, 75, 72, 73, 74,
	0, 0, 59, 60, 61, 62, 63, 64, 65, 66,
	70, 71, 0, 0, 58, 57, 0, 0, 56, 67,
	68, 69, 0, 201, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 76, 77, 0, 0, 0, 75, 72,
	73, 74, 0, 0, 59, 60, 61, 62, 63, 64,
	65, 66, 70, 71, 0, 0, 58, 57, 0, 0,
	56, 67, 68, 69, 213, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 76, 77, 0, 0, 0,
	75, 72, 73, 74, 0, 0, 59, 60, 61, 62,
	63, 64, 65, 66, 70, 71, 0, 0, 58, 57,
	0, 0, 56, 67, 68, 69, 192, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 76, 77, 78,
	79, 80, 75, 72, 73, 74, 0, 0, 59, 60,
	61, 62, 63, 64, 65, 66, 70, 71, 0, 0,
	58, 57, 24, 0, 56, 67, 68, 69, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 76,
	77, 0, 0, 0, 75, 72, 73, 74, 0, 0,
	59, 60, 61, 62, 63, 64, 65, 66, 70, 71,
	0, 0, 58, 57, 0, 0, 56, 0, 227, 67,
	68, 69, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 76, 77, 0, 0, 0, 75, 72,
	73, 74, 0, 0, 59, 60, 61, 62, 63, 64,
	65, 66, 70, 71, 0, 0, 58, 57, 0, 0,
	56, 0, 209, 67, 68, 69, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 76, 77, 78,
	79, 80, 75, 72, 73, 74, 0, 0, 59, 60,
	61, 62, 63, 64, 65, 66, 70, 71, 0, 0,
	58, 57, 0, 0, 56, 67, 68, 69, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 76,
	77, 0, 0, 0, 75, 72, 73, 74, 0, 0,
	59, 60, 61, 62, 63, 64, 65, 66, 70, 71,
	0, 0, 58, 57, 0, 0, 56, 170, 67, 68,
	69, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 76, 77, 0, 0, 0, 75, 72, 73,
	74, 0, 0, 59, 60, 61, 62, 63, 64, 65,
	66, 70, 71, 0, 0, 58, 57, 24, 0, 56,
	67, 68, 69, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 76, 77, 0, 0, 0, 75,
	72, 73, 74, 0, 0, 59, 60, 61, 62, 63,
	64, 65, 66, 70, 71, 0, 0, 58, 57, 0,
	0, 56, 67, 68, 69, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 76, 0, 0, 0,
	0, 75, 72, 73, 74, 0, 0, 59, 60, 61,
	62, 63, 64, 65, 66, 70, 71, 0, 0, 58,
	57, 0, 0, 56, 67, 68, 69, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 75, 72, 73, 74, 0, 0, 59,
	60, 61, 62, 63, 64, 65, 66, 70, 71, 0,
	0, 58, 57, 0, 0, 56, 75, 72, 73, 74,
	0, 0, 59, 60, 61, 62, 63, 64, 65, 66,
	70, 71, 0, 0, 58, 57, 0, 0, 56, 75,
	72, 73, 74, 0, 0, 59, 60, 61, 62, 63,
	64, 65, 66, 0, 0, 0, 0, 58, 57, 0,
	0, 56, 83, 84, 85, 86, 87, 88, 89, 90,
	91, 92, 93, 83, 84, 85, 86, 87, 88, 89,
	90, 91, 92, 93, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 169, 0, 0, 0, 0, 81,
	0, 0, 0, 0, 0, 82, 0, 0, 0, 0,
	81,
}

var DobyPact = [...]int16{
	306, -1000, 26, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 771, 1078,
	394, 394, -1000, -1000, 306, 394, 306, -3, 226, 97,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 394, 394,
	394, 408, -9, 91, 306, 306, 116, 362, 394, 394,
	394, 394, 394, 394, 394, 394, 394, 394, 394, 394,
	394, 394, 394, 394, 394, 394, 394, 394, 394, -1000,
	-1000, 385, 394, 394, 394, 394, 394, 394, 394, 394,
	394, 394, 394, 394, -1000, 898, -15, 898, 54, 856,
	-3, -1000, 39, -44, 394, 641, 1067, -1000, 813, -10,
	982, -36, 394, 314, 394, 114, 5, -1000, -1000, -1000,
	468, 394, -7, 107, 107, -10, -10, -10, 113, 411,
	113, 1005, 1005, 1005, 1028, 1028, 136, 136, 136, 136,
	982, 940, 898, 898, 394, -15, -15, -15, -15, -15,
	-15, -15, -15, -15, -15, -15, -15, -1000, 306, -57,
	-1000, -50, -1000, -1000, 394, -46, 394, 599, -1000, 282,
	-1000, -1000, 109, -37, 394, 48, -1000, 515, -16, 112,
	94, 86, -1000, 727, -1000, 898, 306, -1000, -1000, -41,
	306, 557, 306, 394, -21, -1000, -1000, 87, 394, 80,
	-1000, 394, 110, -5, -31, -19, -1000, 683, -1000, -1000,
	-1000, 306, 23, 306, -5, 856, -1000, -25, -1000, -1000,
	-1000, 394, 898, -1000, -1000, 102, -5, -1000, 23, -5,
	-1000, -1000, -1000, -1000, 3, -1000, -1000, 94, -32, -5,
	-1000,
}

var DobyPgo = [...]uint8{
	0, 0, 24, 213, 211, 210, 209, 208, 207, 116,
	205, 201, 196, 195, 192, 168, 4, 188, 3, 57,
	183, 181, 172, 169, 158, 144, 143, 2, 138, 8,
	5, 133, 132, 131, 127, 126, 7, 125, 120,
}

var DobyR1 = [...]int8{
	0, 2, 3, 3, 3, 3, 4, 5, 7, 7,
	7, 6, 15, 15, 15, 15, 9, 10, 10, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
	12, 14, 14, 14, 16, 17, 17, 17, 17, 17,
	17, 17, 13, 18, 18, 18, 8, 8, 8, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 20, 21, 22, 22, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 24, 25,
	26, 26, 27, 28, 28, 29, 29, 37, 37, 37,
	30, 31, 32, 33, 33, 33, 34, 35, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 36, 36, 36, 36, 36, 38,
}

var DobyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 3, 3, 6, 5,
	5, 4, 0, 1, 3, 4, 4, 2, 2, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 5,
	4, 4, 6, 5, 3, 0, 1, 3, 3, 4,
	2, 3, 4, 0, 1, 3, 5, 6, 10, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 2, 2, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 2,
	1, 1, 3, 3, 5, 4, 3, 1, 1, 2,
	3, 3, 2, 7, 6, 3, 6, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 0, 1, 3, 3, 2, 2,
}

var DobyChk = [...]int16{
	-1000, -38, -36, -19, -20, -21, -22, -23, -24, -25,
	-26, -27, -28, -31, -32, -33, -34, -35, -1, -15,
	70, 78, 59, 62, 51, 72, 81, 79, 68, 73,
	-2, -3, -4, -5, -6, -7, -9, -10, -11, -12,
	-13, -14, -8, 7, 8, 9, 10, 11, 49, 38,
	48, 50, 85, 69, 5, 57, 53, 50, 49, 37,
	38, 39, 40, 41, 42, 43, 44, 12, 13, 14,
	45, 46, 32, 33, 34, 31, 26, 27, 28, 29,
	30, 52, 47, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, -9, -1, -15, -1, -36, -1,
	-19, -30, 51, -19, 57, -1, -15, 10, -1, -1,
	-1, -15, 5, 50, 51, 49, 7, -19, -19, -2,
	-1, 58, -15, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, 5, -15, -15, -15, -15, -15,
	-15, -15, -15, -15, -15, -15, -15, 56, 5, -27,
	-30, -37, 5, -29, 60, 64, 57, -1, -27, 47,
	54, 55, -15, -15, 5, -17, -16, -1, -18, 7,
	49, 58, 55, -1, 54, -1, 66, -29, 56, -15,
	58, -1, 57, 77, 5, 55, 55, -15, 5, 52,
	56, 58, 52, 54, 7, -18, 7, -1, 55, 55,
	-19, 58, -36, 57, -19, -1, 55, 5, 55, -16,
	-16, 5, -1, 7, -27, 54, 54, 55, -36, -19,
	-27, -27, 55, -16, 7, -27, -27, 49, -18, 54,
	-27,
}

var DobyDef = [...]int8{
	-2, -2, 0, 123, 108, 109, 110, 111, 112, 113,
	114, 115, 116, 117, 118, 119, 120, 121, -2, 0,
	0, 12, 90, 91, -2, 0, 12, 0, 12, 0,
	59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
	69, 70, 71, 1, 2, 3, 4, 5, 0, 0,
	0, 12, 0, 0, -2, 12, 0, 0, 12, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 74,
	75, 0, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, -2, 0, 89, 13, 0, 0,
	0, 102, 0, 0, 0, -2, 0, 107, 0, 17,
	18, 0, 12, 12, 45, 53, 0, 124, 125, 7,
	0, 0, 0, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
	36, 37, 73, 14, 0, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 86, 87, 92, -2, 93,
	101, 0, 97, 98, 12, 0, 0, 0, 105, 12,
	6, 38, 0, 0, 12, 0, 46, 0, 0, 54,
	53, 0, 11, 0, 16, 15, 12, 99, 100, 0,
	-2, 0, 12, 0, 0, 40, 41, 0, 50, 0,
	52, 0, 0, 0, 0, 0, 54, 0, 10, 9,
	94, -2, 96, 12, 0, 0, 39, 0, 43, 47,
	48, 51, 44, 55, 56, 0, 0, 8, 95, 0,
	104, 106, 42, 49, 0, 57, 103, 53, 0, 0,
	58,
}

var DobyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 85,
}

var DobyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84,
}

var DobyTok3 = [...]int8{
	0,
}

var DobyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	DobyDebug        = 0
	DobyErrorVerbose = false
)

type DobyLexer interface {
	Lex(lval *DobySymType) int
	Error(s string)
}

type DobyParser interface {
	Parse(DobyLexer) int
	Lookahead() int
}

type DobyParserImpl struct {
	lval  DobySymType
	stack [DobyInitialStackSize]DobySymType
	char  int
}

func (p *DobyParserImpl) Lookahead() int {
	return p.char
}

func DobyNewParser() DobyParser {
	return &DobyParserImpl{}
}

const DobyFlag = -1000

func DobyTokname(c int) string {
	if c >= 1 && c-1 < len(DobyToknames) {
		if DobyToknames[c-1] != "" {
			return DobyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func DobyStatname(s int) string {
	if s >= 0 && s < len(DobyStatenames) {
		if DobyStatenames[s] != "" {
			return DobyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func DobyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !DobyErrorVerbose {
		return "syntax error"
	}

	for _, e := range DobyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + DobyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(DobyPact[state])
	for tok := TOKSTART; tok-1 < len(DobyToknames); tok++ {
		if n := base + tok; n >= 0 && n < DobyLast && int(DobyChk[int(DobyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if DobyDef[state] == -2 {
		i := 0
		for DobyExca[i] != -1 || int(DobyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; DobyExca[i] >= 0; i += 2 {
			tok := int(DobyExca[i])
			if tok < TOKSTART || DobyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if DobyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += DobyTokname(tok)
	}
	return res
}

func Dobylex1(lex DobyLexer, lval *DobySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(DobyTok1[0])
		goto out
	}
	if char < len(DobyTok1) {
		token = int(DobyTok1[char])
		goto out
	}
	if char >= DobyPrivate {
		if char < DobyPrivate+len(DobyTok2) {
			token = int(DobyTok2[char-DobyPrivate])
			goto out
		}
	}
	for i := 0; i < len(DobyTok3); i += 2 {
		token = int(DobyTok3[i+0])
		if token == char {
			token = int(DobyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(DobyTok2[1]) /* unknown char */
	}
	if DobyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", DobyTokname(token), uint(char))
	}
	return char, token
}

func DobyParse(Dobylex DobyLexer) int {
	return DobyNewParser().Parse(Dobylex)
}

func (Dobyrcvr *DobyParserImpl) Parse(Dobylex DobyLexer) int {
	var Dobyn int
	var DobyVAL DobySymType
	var DobyDollar []DobySymType
	_ = DobyDollar // silence set and not used
	DobyS := Dobyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Dobystate := 0
	Dobyrcvr.char = -1
	Dobytoken := -1 // Dobyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Dobystate = -1
		Dobyrcvr.char = -1
		Dobytoken = -1
	}()
	Dobyp := -1
	goto Dobystack

ret0:
	return 0

ret1:
	return 1

Dobystack:
	/* put a state and value onto the stack */
	if DobyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", DobyTokname(Dobytoken), DobyStatname(Dobystate))
	}

	Dobyp++
	if Dobyp >= len(DobyS) {
		nyys := make([]DobySymType, len(DobyS)*2)
		copy(nyys, DobyS)
		DobyS = nyys
	}
	DobyS[Dobyp] = DobyVAL
	DobyS[Dobyp].yys = Dobystate

Dobynewstate:
	Dobyn = int(DobyPact[Dobystate])
	if Dobyn <= DobyFlag {
		goto Dobydefault /* simple state */
	}
	if Dobyrcvr.char < 0 {
		Dobyrcvr.char, Dobytoken = Dobylex1(Dobylex, &Dobyrcvr.lval)
	}
	Dobyn += Dobytoken
	if Dobyn < 0 || Dobyn >= DobyLast {
		goto Dobydefault
	}
	Dobyn = int(DobyAct[Dobyn])
	if int(DobyChk[Dobyn]) == Dobytoken { /* valid shift */
		Dobyrcvr.char = -1
		Dobytoken = -1
		DobyVAL = Dobyrcvr.lval
		Dobystate = Dobyn
		if Errflag > 0 {
			Errflag--
		}
		goto Dobystack
	}

Dobydefault:
	/* default state action */
	Dobyn = int(DobyDef[Dobystate])
	if Dobyn == -2 {
		if Dobyrcvr.char < 0 {
			Dobyrcvr.char, Dobytoken = Dobylex1(Dobylex, &Dobyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if DobyExca[xi+0] == -1 && int(DobyExca[xi+1]) == Dobystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Dobyn = int(DobyExca[xi+0])
			if Dobyn < 0 || Dobyn == Dobytoken {
				break
			}
		}
		Dobyn = int(DobyExca[xi+1])
		if Dobyn < 0 {
			goto ret0
		}
	}
	if Dobyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Dobylex.Error(DobyErrorMessage(Dobystate, Dobytoken))
			Nerrs++
			if DobyDebug >= 1 {
				__yyfmt__.Printf("%s", DobyStatname(Dobystate))
				__yyfmt__.Printf(" saw %s\n", DobyTokname(Dobytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Dobyp >= 0 {
				Dobyn = int(DobyPact[DobyS[Dobyp].yys]) + DobyErrCode
				if Dobyn >= 0 && Dobyn < DobyLast {
					Dobystate = int(DobyAct[Dobyn]) /* simulate a shift of "error" */
					if int(DobyChk[Dobystate]) == DobyErrCode {
						goto Dobystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if DobyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", DobyS[Dobyp].yys)
				}
				Dobyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if DobyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", DobyTokname(Dobytoken))
			}
			if Dobytoken == DobyEofCode {
				goto ret1
			}
			Dobyrcvr.char = -1
			Dobytoken = -1
			goto Dobynewstate /* try again in the same state */
		}
	}

	/* reduction by production Dobyn */
	if DobyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Dobyn, DobyStatname(Dobystate))
	}

	Dobynt := Dobyn
	Dobypt := Dobyp
	_ = Dobypt // guard against "declared and not used"

	Dobyp -= int(DobyR2[Dobyn])
	// Dobyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Dobyp+1 >= len(DobyS) {
		nyys := make([]DobySymType, len(DobyS)*2)
		copy(nyys, DobyS)
		DobyS = nyys
	}
	DobyVAL = DobyS[Dobyp+1]

	/* consult goto table to find next state */
	Dobyn = int(DobyR1[Dobyn])
	Dobyg := int(DobyPgo[Dobyn])
	Dobyj := Dobyg + DobyS[Dobyp].yys + 1

	if Dobyj >= DobyLast {
		Dobystate = int(DobyAct[Dobyg])
	} else {
		Dobystate = int(DobyAct[Dobyj])
		if int(DobyChk[Dobystate]) != -Dobyn {
			Dobystate = int(DobyAct[Dobyg])
		}
	}
	// dummy call; replaced with literal code
	switch Dobynt {

	case 1:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:90
		{
			DobyVAL.expr = &ast.Ident{DobyDollar[1].tok.Pos, DobyDollar[1].tok.Lit}
		}
	case 2:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:92
		{
			DobyVAL.expr = &ast.BasicLit{DobyDollar[1].tok.Pos, token.INT, DobyDollar[1].tok.Lit}
		}
	case 3:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:93
		{
			DobyVAL.expr = &ast.BasicLit{DobyDollar[1].tok.Pos, token.FLOAT, DobyDollar[1].tok.Lit}
		}
	case 4:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:94
		{
			DobyVAL.expr = &ast.BasicLit{DobyDollar[1].tok.Pos, token.STRING, DobyDollar[1].tok.Lit}
		}
	case 5:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:95
		{
			DobyVAL.expr = &ast.BasicLit{DobyDollar[1].tok.Pos, token.CHAR, DobyDollar[1].tok.Lit}
		}
	case 6:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:97
		{
			DobyVAL.expr = &ast.ParenExpr{DobyDollar[1].tok.Pos, DobyDollar[2].expr, DobyDollar[3].tok.Pos}
		}
	case 7:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:99
		{
			DobyVAL.expr = &ast.SelectorExpr{DobyDollar[1].expr, DobyDollar[3].expr.(*ast.Ident)}
		}
	case 8:
		DobyDollar = DobyS[Dobypt-6 : Dobypt+1]
//line grammar.y:102
		{
			DobyVAL.expr = &ast.SliceExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, DobyDollar[3].expr, DobyDollar[5].expr, DobyDollar[6].tok.Pos}
		}
	case 9:
		DobyDollar = DobyS[Dobypt-5 : Dobypt+1]
//line grammar.y:104
		{
			DobyVAL.expr = &ast.SliceExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, nil, DobyDollar[4].expr, DobyDollar[5].tok.Pos}
		}
	case 10:
		DobyDollar = DobyS[Dobypt-5 : Dobypt+1]
//line grammar.y:106
		{
			DobyVAL.expr = &ast.SliceExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, DobyDollar[3].expr, nil, DobyDollar[5].tok.Pos}
		}
	case 11:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:109
		{
			DobyVAL.expr = &ast.IndexExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, DobyDollar[3].expr, DobyDollar[2].tok.Pos}
		}
	case 12:
		DobyDollar = DobyS[Dobypt-0 : Dobypt+1]
//line grammar.y:111
		{
			DobyVAL.expr_list = []ast.Expr{}
		}
	case 13:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:112
		{
			DobyVAL.expr_list = []ast.Expr{DobyDollar[1].expr}
		}
	case 14:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:113
		{
			DobyVAL.expr_list = append(DobyDollar[1].expr_list, DobyDollar[3].expr)
		}
	case 15:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:114
		{
			DobyVAL.expr_list = append(DobyDollar[1].expr_list, DobyDollar[4].expr)
		}
	case 16:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:116
		{
			DobyVAL.expr = &ast.CallExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, DobyDollar[3].expr_list, DobyDollar[4].tok.Pos}
		}
	case 17:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:118
		{
			DobyVAL.expr = &ast.UnaryExpr{DobyDollar[1].tok.Pos, token.SUB, DobyDollar[2].expr}
		}
	case 18:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:119
		{
			DobyVAL.expr = &ast.UnaryExpr{DobyDollar[1].tok.Pos, token.NOT, DobyDollar[2].expr}
		}
	case 19:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:121
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.ADD, DobyDollar[3].expr}
		}
	case 20:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:122
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.SUB, DobyDollar[3].expr}
		}
	case 21:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:123
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.MUL, DobyDollar[3].expr}
		}
	case 22:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:124
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.QUO, DobyDollar[3].expr}
		}
	case 23:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:125
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.REM, DobyDollar[3].expr}
		}
	case 24:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:126
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.AND, DobyDollar[3].expr}
		}
	case 25:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:127
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.OR, DobyDollar[3].expr}
		}
	case 26:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:128
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.XOR, DobyDollar[3].expr}
		}
	case 27:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:129
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.SHL, DobyDollar[3].expr}
		}
	case 28:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:130
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.SHR, DobyDollar[3].expr}
		}
	case 29:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:131
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.AND_NOT, DobyDollar[3].expr}
		}
	case 30:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:132
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.LSS, DobyDollar[3].expr}
		}
	case 31:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:133
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.GTR, DobyDollar[3].expr}
		}
	case 32:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:134
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.NEQ, DobyDollar[3].expr}
		}
	case 33:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:135
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.LEQ, DobyDollar[3].expr}
		}
	case 34:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:136
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.GEQ, DobyDollar[3].expr}
		}
	case 35:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:137
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.EQL, DobyDollar[3].expr}
		}
	case 36:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:139
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.LAND, DobyDollar[3].expr}
		}
	case 37:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:140
		{
			DobyVAL.expr = &ast.BinaryExpr{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.LOR, DobyDollar[3].expr}
		}
	case 38:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:143
		{
			DobyVAL.expr = &ast.ArrayExpr{DobyDollar[1].tok.Pos, DobyDollar[2].expr_list, DobyDollar[3].tok.Pos}
		}
	case 39:
		DobyDollar = DobyS[Dobypt-5 : Dobypt+1]
//line grammar.y:145
		{
			DobyVAL.expr = &ast.ArrayExpr{DobyDollar[1].tok.Pos, DobyDollar[3].expr_list, DobyDollar[4].tok.Pos}
		}
	case 40:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:147
		{
			DobyVAL.expr = &ast.ArrayExpr{DobyDollar[1].tok.Pos, DobyDollar[3].expr_list, DobyDollar[4].tok.Pos}
		}
	case 41:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:150
		{
			DobyVAL.expr = &ast.SetExpr{DobyDollar[2].tok.Pos, DobyDollar[3].expr_list, DobyDollar[4].tok.Pos}
		}
	case 42:
		DobyDollar = DobyS[Dobypt-6 : Dobypt+1]
//line grammar.y:152
		{
			DobyVAL.expr = &ast.SetExpr{DobyDollar[2].tok.Pos, DobyDollar[4].expr_list, DobyDollar[6].tok.Pos}
		}
	case 43:
		DobyDollar = DobyS[Dobypt-5 : Dobypt+1]
//line grammar.y:154
		{
			DobyVAL.expr = &ast.SetExpr{DobyDollar[2].tok.Pos, DobyDollar[4].expr_list, DobyDollar[5].tok.Pos}
		}
	case 44:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:157
		{
			DobyVAL.field = &ast.Field{DobyDollar[1].expr, DobyDollar[2].tok.Pos, DobyDollar[3].expr}
		}
	case 45:
		DobyDollar = DobyS[Dobypt-0 : Dobypt+1]
//line grammar.y:159
		{
			DobyVAL.field_list = []*ast.Field{}
		}
	case 46:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:160
		{
			DobyVAL.field_list = []*ast.Field{DobyDollar[1].field}
		}
	case 47:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:161
		{
			DobyVAL.field_list = append(DobyDollar[1].field_list, DobyDollar[3].field)
		}
	case 48:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:162
		{
			DobyVAL.field_list = append(DobyDollar[1].field_list, DobyDollar[3].field)
		}
	case 49:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:163
		{
			DobyVAL.field_list = append(DobyDollar[1].field_list, DobyDollar[4].field)
		}
	case 50:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:164
		{
			DobyVAL.field_list = DobyDollar[1].field_list
		}
	case 51:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:165
		{
			DobyVAL.field_list = DobyDollar[1].field_list
		}
	case 52:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:168
		{
			DobyVAL.expr = &ast.DictExpr{DobyDollar[2].tok.Pos, DobyDollar[3].field_list, DobyDollar[4].tok.Pos}
		}
	case 53:
		DobyDollar = DobyS[Dobypt-0 : Dobypt+1]
//line grammar.y:171
		{
			DobyVAL.ident_list = []*ast.Ident{}
		}
	case 54:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:173
		{
			DobyVAL.ident_list = []*ast.Ident{&ast.Ident{DobyDollar[1].tok.Pos, DobyDollar[1].tok.Lit}}
		}
	case 55:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:175
		{
			DobyVAL.ident_list = append(DobyDollar[1].ident_list, &ast.Ident{DobyDollar[3].tok.Pos, DobyDollar[3].tok.Lit})
		}
	case 56:
		DobyDollar = DobyS[Dobypt-5 : Dobypt+1]
//line grammar.y:178
		{
			DobyVAL.expr = &ast.FuncDeclExpr{DobyDollar[1].tok.Pos, nil, nil, nil, DobyDollar[3].ident_list, DobyDollar[5].stmt.(*ast.BlockStmt), []string{}}
		}
	case 57:
		DobyDollar = DobyS[Dobypt-6 : Dobypt+1]
//line grammar.y:180
		{
			DobyVAL.expr = &ast.FuncDeclExpr{DobyDollar[1].tok.Pos, nil, nil, &ast.Ident{DobyDollar[2].tok.Pos, DobyDollar[2].tok.Lit}, DobyDollar[4].ident_list, DobyDollar[6].stmt.(*ast.BlockStmt), []string{}}
		}
	case 58:
		DobyDollar = DobyS[Dobypt-10 : Dobypt+1]
//line grammar.y:182
		{
			DobyVAL.expr = &ast.FuncDeclExpr{DobyDollar[1].tok.Pos, &ast.Ident{DobyDollar[3].tok.Pos, DobyDollar[3].tok.Lit}, &ast.Ident{DobyDollar[4].tok.Pos, DobyDollar[4].tok.Lit},
				&ast.Ident{DobyDollar[6].tok.Pos, DobyDollar[6].tok.Lit}, DobyDollar[8].ident_list, DobyDollar[10].stmt.(*ast.BlockStmt), []string{}}
		}
	case 72:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:201
		{
			DobyVAL.stmt = &ast.ExprStmt{DobyDollar[1].expr}
		}
	case 73:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:203
		{
			DobyVAL.stmt = &ast.SendStmt{DobyDollar[1].expr, DobyDollar[2].tok.Pos, DobyDollar[3].expr}
		}
	case 74:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:205
		{
			DobyVAL.stmt = &ast.IncDecStmt{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.INC}
		}
	case 75:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:206
		{
			DobyVAL.stmt = &ast.IncDecStmt{DobyDollar[1].expr, DobyDollar[2].tok.Pos, token.DEC}
		}
	case 76:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:208
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.ASSIGN, DobyDollar[3].expr_list}
		}
	case 77:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:209
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.ADD_ASSIGN, DobyDollar[3].expr_list}
		}
	case 78:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:210
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.SUB_ASSIGN, DobyDollar[3].expr_list}
		}
	case 79:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:211
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.MUL_ASSIGN, DobyDollar[3].expr_list}
		}
	case 80:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:212
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.QUO_ASSIGN, DobyDollar[3].expr_list}
		}
	case 81:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:213
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.REM_ASSIGN, DobyDollar[3].expr_list}
		}
	case 82:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:214
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.AND_ASSIGN, DobyDollar[3].expr_list}
		}
	case 83:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:215
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.OR_ASSIGN, DobyDollar[3].expr_list}
		}
	case 84:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:216
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.XOR_ASSIGN, DobyDollar[3].expr_list}
		}
	case 85:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:217
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.SHL_ASSIGN, DobyDollar[3].expr_list}
		}
	case 86:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:218
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.SHR_ASSIGN, DobyDollar[3].expr_list}
		}
	case 87:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:219
		{
			DobyVAL.stmt = &ast.AssignStmt{DobyDollar[1].expr_list, DobyDollar[2].tok.Pos, token.AND_NOT_ASSIGN, DobyDollar[3].expr_list}
		}
	case 88:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:222
		{
			DobyVAL.stmt = &ast.GoStmt{DobyDollar[1].tok.Pos, DobyDollar[2].expr.(*ast.CallExpr)}
		}
	case 89:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:225
		{
			DobyVAL.stmt = &ast.ReturnStmt{DobyDollar[1].tok.Pos, DobyDollar[2].expr_list}
		}
	case 90:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:227
		{
			DobyVAL.stmt = &ast.BranchStmt{DobyDollar[1].tok.Pos, token.BREAK}
		}
	case 91:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:228
		{
			DobyVAL.stmt = &ast.BranchStmt{DobyDollar[1].tok.Pos, token.CONTINUE}
		}
	case 92:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:230
		{
			DobyVAL.stmt = &ast.BlockStmt{DobyDollar[1].tok.Pos, DobyDollar[2].stmt_list, DobyDollar[3].tok.Pos}
		}
	case 93:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:232
		{
			DobyVAL.stmt = &ast.IfStmt{DobyDollar[1].tok.Pos, DobyDollar[2].expr, DobyDollar[3].stmt.(*ast.BlockStmt), nil}
		}
	case 94:
		DobyDollar = DobyS[Dobypt-5 : Dobypt+1]
//line grammar.y:233
		{
			DobyVAL.stmt = &ast.IfStmt{DobyDollar[1].tok.Pos, DobyDollar[2].expr, DobyDollar[3].stmt.(*ast.BlockStmt), DobyDollar[5].stmt}
		}
	case 95:
		DobyDollar = DobyS[Dobypt-4 : Dobypt+1]
//line grammar.y:235
		{
			DobyVAL.stmt = &ast.CaseClause{DobyDollar[1].tok.Pos, DobyDollar[2].expr_list, DobyDollar[3].tok.Pos, DobyDollar[4].stmt_list}
		}
	case 96:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:236
		{
			DobyVAL.stmt = &ast.CaseClause{DobyDollar[1].tok.Pos, nil, DobyDollar[2].tok.Pos, DobyDollar[3].stmt_list}
		}
	case 97:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:238
		{
			DobyVAL.stmt_list = []ast.Stmt{}
		}
	case 98:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:239
		{
			DobyVAL.stmt_list = []ast.Stmt{DobyDollar[1].stmt}
		}
	case 99:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:240
		{
			DobyVAL.stmt_list = append(DobyDollar[1].stmt_list, DobyDollar[2].stmt)
		}
	case 100:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:242
		{
			DobyVAL.stmt = &ast.BlockStmt{DobyDollar[1].tok.Pos, DobyDollar[2].stmt_list, DobyDollar[3].tok.Pos}
		}
	case 101:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:244
		{
			DobyVAL.stmt = &ast.SwitchStmt{DobyDollar[1].tok.Pos, DobyDollar[2].stmt, DobyDollar[3].stmt.(*ast.BlockStmt)}
		}
	case 102:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:246
		{
			DobyVAL.stmt = &ast.SelectStmt{DobyDollar[1].tok.Pos, DobyDollar[2].stmt.(*ast.BlockStmt)}
		}
	case 103:
		DobyDollar = DobyS[Dobypt-7 : Dobypt+1]
//line grammar.y:249
		{
			DobyVAL.stmt = &ast.ForStmt{DobyDollar[1].tok.Pos, DobyDollar[2].stmt, DobyDollar[4].expr, DobyDollar[6].stmt, DobyDollar[7].stmt.(*ast.BlockStmt)}
		}
	case 104:
		DobyDollar = DobyS[Dobypt-6 : Dobypt+1]
//line grammar.y:251
		{
			DobyVAL.stmt = &ast.ForStmt{DobyDollar[1].tok.Pos, nil, DobyDollar[3].expr, DobyDollar[5].stmt, DobyDollar[6].stmt.(*ast.BlockStmt)}
		}
	case 105:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:253
		{
			DobyVAL.stmt = &ast.ForStmt{DobyDollar[1].tok.Pos, nil, DobyDollar[2].expr, nil, DobyDollar[3].stmt.(*ast.BlockStmt)}
		}
	case 106:
		DobyDollar = DobyS[Dobypt-6 : Dobypt+1]
//line grammar.y:256
		{
			DobyVAL.stmt = &ast.RangeStmt{DobyDollar[1].tok.Pos, DobyDollar[2].expr_list, DobyDollar[5].expr, DobyDollar[6].stmt.(*ast.BlockStmt)}
		}
	case 107:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:259
		{
			DobyVAL.stmt = &ast.ImportStmt{DobyDollar[1].tok.Pos, []string{DobyDollar[2].tok.Lit}}
		}
	case 122:
		DobyDollar = DobyS[Dobypt-0 : Dobypt+1]
//line grammar.y:276
		{
			DobyVAL.stmt_list = []ast.Stmt{}
		}
	case 123:
		DobyDollar = DobyS[Dobypt-1 : Dobypt+1]
//line grammar.y:277
		{
			DobyVAL.stmt_list = []ast.Stmt{DobyDollar[1].stmt}
		}
	case 124:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:278
		{
			DobyVAL.stmt_list = append(DobyDollar[1].stmt_list, DobyDollar[3].stmt)
		}
	case 125:
		DobyDollar = DobyS[Dobypt-3 : Dobypt+1]
//line grammar.y:279
		{
			DobyVAL.stmt_list = append(DobyDollar[1].stmt_list, DobyDollar[3].stmt)
		}
	case 126:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:280
		{
			DobyVAL.stmt_list = DobyDollar[1].stmt_list
		}
	case 127:
		DobyDollar = DobyS[Dobypt-2 : Dobypt+1]
//line grammar.y:285
		{
			ProgramAst = DobyDollar[1].stmt_list
		}
	}
	goto Dobystack /* stack new state and value */
}
